// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zadspxqsvwkvlfcctjod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZHNweHFzdndrdmxmY2N0am9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzI3ODIsImV4cCI6MjA2ODk0ODc4Mn0.hTiZwIziAFMQhc5X7FwVGuk3XnbDxl29EPckbxBz-00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});